using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Threading;
using System.Diagnostics;
static class IntegrationTests {
 static Dictionary<string,object> A(params object[] p){var d=new Dictionary<string,object>();for(int i=0;i<p.Length;i+=2)d.Add((string)p[i],p[i+1]);return d;}
 static Dictionary<string,object> O(object v){return Core.Json().Deserialize<Dictionary<string,object>>(Core.Json().Serialize(v));}
 static void Assert(bool b,string s){if(!b)throw new Exception(s);}
 static object Request(string name,object args){return DesktopIntegration.Call("desktop_request",A("tool",name,"arguments_json",Core.Json().Serialize(args),"reason","Synthetic integration fixture; isolated test only"));}
 static Dictionary<string,object> Wait(Dictionary<string,object> req){for(int i=0;i<1400;i++){var r=O(DesktopIntegration.Call("desktop_result",A("request_token",req["request_token"])));if((string)r["state"]=="completed")return r;if((string)r["state"]=="failed")throw new Exception((string)r["error"]);Thread.Sleep(100);}throw new Exception("Request test deadline");}
 static Dictionary<string,object> Approved(string name,object args){var req=O(Request(name,args));if((string)req["state"]=="pending")DesktopIntegration.Decide((string)req["request_id"],true);var result=Wait(req);var upstream=O(Core.Json().DeserializeObject((string)result["result_json"]));if(upstream.ContainsKey("isError")&&(bool)upstream["isError"])throw new Exception((string)result["result_json"]);return result;}
 public static int Run(){if(!Core.Instance.StartsWith("PCBridge-Integrated-Test-"))return 9;var passed=new List<string>();string report=Path.Combine(Path.GetDirectoryName(Core.Self),"integration-tests.json");try{
  Core.Prepare();ScopeEngine.ServerStart();DesktopIntegration.Start();Assert(Core.Load()==null,"No credentials in fresh bundle");passed.Add("fresh isolated bundle has no API key or inherited settings");
  string companionRoot=Path.Combine(Core.Root,"provider","chatgpt-extension");
  Assert(File.Exists(Path.Combine(companionRoot,"manifest.json"))&&
         File.Exists(Path.Combine(companionRoot,"background.js"))&&
         File.Exists(Path.Combine(companionRoot,"content.js"))&&
         File.Exists(Path.Combine(companionRoot,"chatgpt-dom.js")),"M1 companion payload files missing");
  passed.Add("M1 ChatGPT companion files are embedded and extracted into the isolated runtime");

  var catalog=O(DesktopIntegration.Call("desktop_tools",A()));var tools=(IList)catalog["tools"];Assert(tools.Count>=20,"Desktop tools discovered");passed.Add("real bundled Node + Desktop Commander initialized over stdio; "+tools.Count+" upstream tools discovered");
  Assert(DesktopIntegration.Tools().Any(x=>Core.Json().Serialize(x).Contains("\"desktop_relay\"")),"desktop_relay schema missing");var relayStatus=O(DesktopIntegration.Call("desktop_relay",A("action","status")));Assert(relayStatus.ContainsKey("binding")&&relayStatus.ContainsKey("latest"),"desktop_relay status shape invalid");passed.Add("built-in desktop_relay tool is registered and status is queryable without UI side effects");
  var allSchemas=ScopeEngine.Tools().Select(x=>Core.Json().Serialize(x)).ToArray();
  Assert(allSchemas.Any(x=>x.Contains("\"automation_prepare\""))&&allSchemas.Any(x=>x.Contains("\"automation_handoff\""))&&allSchemas.Any(x=>x.Contains("\"automation_complete\"")),"M1 automation schemas missing");
  string automationSession="integration-session-"+Guid.NewGuid().ToString("N");
  var prepare=O(M1McpIntegration.Call("automation_prepare",A("session_id",automationSession)));
  Assert((string)prepare["state"]=="BINDING_REQUIRED","unbound M1 session must fail closed");
  var m1Runtime=O(prepare["runtime"]);
  Assert(Convert.ToBoolean(m1Runtime["companion_ready"]),"M1 runtime did not validate the extracted companion");

  var binding=O(prepare["binding"]);string bindingId=(string)binding["binding_id"];
  const string automationConversation="12345678-abcd-4abc-8abc-123456789012";
  M1McpIntegration.Runtime.Bindings.ProposeCandidate(bindingId,automationConversation,"integration-document");
  M1McpIntegration.Runtime.ConfirmBindingLocal(bindingId,automationConversation,"chatgpt-default");
  var handoff=O(M1McpIntegration.Call("automation_handoff",A("session_id",automationSession,"summary","verified integration work","next_action","continue integration work","verification","integration fixture checked","blocking_state","none")));
  Assert((string)handoff["state"]=="HANDOFF_QUEUED"&&!String.IsNullOrWhiteSpace((string)handoff["message_id"]),"M1 handoff was not durably queued");
  string m1Run=(string)handoff["run_id"];long m1Generation=Convert.ToInt64(handoff["generation"]);string m1Message=(string)handoff["message_id"];
  var repeat=O(M1McpIntegration.Call("automation_handoff",A("run_id",m1Run,"generation",m1Generation,"summary","verified integration work","next_action","continue integration work","verification","integration fixture checked","blocking_state","none")));
  Assert(Convert.ToBoolean(repeat["existing"])&&(string)repeat["message_id"]==m1Message,"M1 run-fenced duplicate did not remain idempotent");
  var complete=O(M1McpIntegration.Call("automation_complete",A("run_id",m1Run,"generation",m1Generation,"verification","integration fixture completed before Send")));
  Assert((string)complete["status"]=="COMPLETED","M1 completion did not cancel unsent baton and terminate run");
  passed.Add("M1 MCP surface binds locally, queues durable handoff, resumes by run fence and completes idempotently");
  string work=Path.Combine(Path.GetDirectoryName(Core.Self),"IntegrationFixtures",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(work);string file=Path.Combine(work,"한국어.txt");
  var req=O(Request("write_file",new{path=file,content="PCBridge 통합 검증 ✓",mode="rewrite"}));Assert((string)req["state"]=="approved","ordinary write should auto-approve");Wait(req);Assert(File.ReadAllText(file).Contains("통합 검증"),"UTF8 write failed");passed.Add("non-HARDLOCK write auto-runs without local approval; Unicode content verified");
  bool denied=false;try{DesktopIntegration.Call("desktop_result",A("request_token","other-chat"));}catch{denied=true;}Assert(denied,"bad token accepted");passed.Add("another caller without request capability cannot read result");
  var read=Approved("read_file",new{path=file});Assert(((string)read["result_json"]).Contains("통합 검증"),"read mismatch");passed.Add("read returns real file content");
  var autoRead=O(Request("read_file",new{path=file}));Assert((string)autoRead["state"]=="approved","read did not auto-approve");var autoReadDone=Wait(autoRead);Assert(((string)autoReadDone["result_json"]).Contains("통합 검증"),"auto read mismatch");passed.Add("read auto-runs without local approval");
  var auth=O(DesktopIntegration.Call("desktop_authorize",A("name","integration compatibility lease","reason","Verify explicit lease remains supported","grade",3,"duration_minutes",60,"capabilities",new{tools=new[]{"write_file"},paths=new[]{work},command_prefixes=new string[0],process_names=new string[0],network=false})));DesktopIntegration.Decide((string)auth["request_id"],true);Wait(auth);string leaseToken=(string)auth["lease_token"];string leasedFile=Path.Combine(work,"leased.txt");var leased=O(DesktopIntegration.Call("desktop_request",A("tool","write_file","arguments_json",Core.Json().Serialize(new{path=leasedFile,content="LEASE_OK",mode="rewrite"}),"reason","lease compatibility fixture","lease_token",leaseToken)));Assert((string)leased["state"]=="approved","explicit lease request was not approved");Wait(leased);Assert(File.ReadAllText(leasedFile)=="LEASE_OK","leased write failed");passed.Add("explicit restricted lease remains compatible");
  string deltaFile=Path.Combine(Path.GetDirectoryName(work),"delta-"+Guid.NewGuid().ToString("N")+".txt");var delta=O(DesktopIntegration.Call("desktop_request",A("tool","write_file","arguments_json",Core.Json().Serialize(new{path=deltaFile,content="DELTA_OK",mode="rewrite"}),"reason","non-hardlock boundary fixture","lease_token",leaseToken)));Assert((string)delta["state"]=="approved","non-HARDLOCK out-of-scope write should auto-run");Wait(delta);Assert(File.ReadAllText(deltaFile)=="DELTA_OK","auto boundary write failed");passed.Add("non-HARDLOCK scope growth no longer prompts");
  string exactDelete=Path.Combine(work,"delete-me.txt");File.WriteAllText(exactDelete,"DELETE_ME");var scopedDelete=O(Request("start_process",new{command="powershell.exe -NoProfile -Command \"Remove-Item -LiteralPath '"+exactDelete+"' -Force\"",timeout_ms=1000,shell="powershell.exe"}));Assert(Convert.ToInt32(scopedDelete["grade"])==2&&(string)scopedDelete["state"]=="approved","exact recoverable delete should auto-run");Wait(scopedDelete);Assert(!File.Exists(exactDelete),"exact delete did not execute");passed.Add("exact scoped deletion auto-runs when it is not classified as high-risk");
  string sentinel=Path.Combine(work,"sentinel.txt");File.WriteAllText(sentinel,"KEEP");var hard=O(Request("start_process",new{command="powershell.exe -NoProfile -Command \"Remove-Item -LiteralPath '"+work+"\\*' -Recurse -Force\"",timeout_ms=1000,shell="powershell.exe"}));Assert(Convert.ToInt32(hard["grade"])==1&&(string)hard["state"]=="pending","recursive wildcard delete was not hardlocked");DesktopIntegration.Decide((string)hard["request_id"],false);Thread.Sleep(300);Assert(File.Exists(sentinel),"denied hardlock executed");passed.Add("recursive/wildcard deletion remains one-shot HARDLOCK");
  var recovery=O(Request("start_process",new{command="cmd.exe /c echo git reflog expire --expire=now --all",timeout_ms=1000,shell="cmd.exe"}));Assert(Convert.ToInt32(recovery["grade"])==1&&(string)recovery["state"]=="pending","recovery/history destruction marker was not hardlocked");DesktopIntegration.Decide((string)recovery["request_id"],false);passed.Add("recovery/history destruction remains HARDLOCK");
  var security=O(Request("start_process",new{command="cmd.exe /c echo Set-MpPreference -DisableRealtimeMonitoring $true",timeout_ms=1000,shell="cmd.exe"}));Assert(Convert.ToInt32(security["grade"])==1&&(string)security["state"]=="pending","security-disable marker was not hardlocked");DesktopIntegration.Decide((string)security["request_id"],false);passed.Add("security disablement remains HARDLOCK");
  var payment=O(Request("start_process",new{command="cmd.exe /c echo checkout payment",timeout_ms=1000,shell="cmd.exe"}));Assert(Convert.ToInt32(payment["grade"])==1&&(string)payment["state"]=="pending","payment marker was not hardlocked");DesktopIntegration.Decide((string)payment["request_id"],false);passed.Add("payment/financial action remains HARDLOCK");
  string bigFile=Path.Combine(work,"large-result.txt");File.WriteAllText(bigFile,new string('A',360000),new System.Text.UTF8Encoding(false));var bigReq=O(Request("read_file",new{path=bigFile}));Assert((string)bigReq["state"]=="approved","large read did not auto-approve");var bigFirst=Wait(bigReq);Assert(Convert.ToInt32(bigFirst["result_length"])>250000&&(bool)bigFirst["has_more"],"large result was not retained/paged");var bigNext=O(DesktopIntegration.Call("desktop_result",A("request_token",bigReq["request_token"],"offset",bigFirst["next_offset"],"count",120000)));Assert(((string)bigNext["result_json"]).Length>0,"second large-result page missing");passed.Add("large results remain locally retained and paged");
  string xlsx=Path.Combine(work,"통합검증.xlsx");Approved("write_file",new{path=xlsx,content="{\"검증\":[[\"항목\",\"값\"],[\"통합\",42]]}"});Assert(File.Exists(xlsx)&&new FileInfo(xlsx).Length>500,"Excel output missing");var excel=Approved("read_file",new{path=xlsx});Assert(((string)excel["result_json"]).Contains("42"),"Excel roundtrip mismatch");passed.Add("Excel workbook roundtrip works");
  var search=Approved("start_search",new{path=work,pattern="통합 검증",searchType="content",timeout_ms=1000});Assert(((string)search["result_json"]).Length>0,"search missing");passed.Add("bundled ripgrep search invoked successfully");
  var proc=Approved("start_process",new{command="Start-Sleep -Seconds 32; Write-Output 'PCBRIDGE_LONG_JOB_OK'",timeout_ms=1000,shell="powershell.exe"});var ps=(string)proc["result_json"];var match=System.Text.RegularExpressions.Regex.Match(ps,@"PID:?\s*(\d+)",System.Text.RegularExpressions.RegexOptions.IgnoreCase);if(!match.Success)throw new Exception("PID missing: "+ps);int pid=Int32.Parse(match.Groups[1].Value);Thread.Sleep(33000);var output=Approved("read_process_output",new{pid=pid,timeout_ms=1000});Assert(((string)output["result_json"]).Contains("PCBRIDGE_LONG_JOB_OK"),"long process output missing");passed.Add("process survives >30 seconds and output is retrievable");
  var config=File.ReadAllText(Path.Combine(Core.Root,"engine","node_modules","@wonderwhy-er","desktop-commander","dist","config.js"));Assert(config.Contains("PCBRIDGE_DC_DATA"),"data path patch absent");Assert(Directory.Exists(Path.Combine(Core.Root,"desktop-data")),"isolated config absent");passed.Add("Desktop Commander private config remains isolated");
  File.WriteAllText(report,Core.Json().Serialize(new{ok=true,version=Core.Version,tests=passed,root=Core.Root}));return 0;
 }catch(Exception e){File.WriteAllText(report,Core.Json().Serialize(new{ok=false,tests=passed,error=e.ToString(),root=Core.Root}));return 1;}finally{M1McpIntegration.Stop();DesktopIntegration.Stop();}}
}