using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows.Forms;
using System.Drawing;

static class ScopeTests {
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool CreateHardLink(string newName,string oldName,IntPtr reserved);
 static Dictionary<string,object> A(params object[] pairs){var a=new Dictionary<string,object>();for(int i=0;i<pairs.Length;i+=2)a.Add((string)pairs[i],pairs[i+1]);return a;}
 static Dictionary<string,object> Obj(object value){return Core.Json().Deserialize<Dictionary<string,object>>(Core.Json().Serialize(value));}
 static object Call(string name,params object[] pairs){return ScopeEngine.Call(name,A(pairs));}
 static object[] Scope(string path,string mode){return new object[]{A("path",path,"mode",mode)};}
 static string NewTask(string path,string mode,out string id){var r=Obj(Call("request_task","name","TEST task","reason","Synthetic fixture only","scopes",Scope(path,mode)));var t=Obj(r["task"]);id=(string)t["task_id"];return (string)r["task_token"];}
 static void Assert(bool b,string why){if(!b)throw new Exception(why);}
 static void Denied(Action f,string why){try{f();}catch{return;}throw new Exception("Expected denial: "+why);}
 static void Shot(Form f,string name){using(f)using(var bmp=new Bitmap(f.Width,f.Height)){f.Show();Application.DoEvents();f.DrawToBitmap(bmp,new Rectangle(0,0,bmp.Width,bmp.Height));f.Hide();bmp.Save(Path.Combine(Path.GetDirectoryName(Core.Self),name));}}
 public static int Run(){
  if(!Core.Instance.StartsWith("PCBridge-Integrated-Test-"))return 9;
  string report=Path.Combine(Path.GetDirectoryName(Core.Self),"scope-tests.json");var tests=new List<string>();
  string work=Path.Combine(Path.GetDirectoryName(Core.Self),"ScopeFixtures",Guid.NewGuid().ToString("N"));
  try{
   Core.Prepare();Assert(File.Exists(Core.Bin)&&new FileInfo(Core.Bin).Length>1000000,"Embedded tunnel runtime missing");Assert(File.Exists(Path.Combine(Core.Root,"runtime","cloudflared.exe")),"Embedded transport runtime missing");tests.Add("real embedded tunnel and transport executables extracted");ScopeEngine.ServerStart();Assert(Core.Load()==null,"No inherited credentials");Assert(ScopeStore.Load().tasks.Count==0,"Fresh permissions");tests.Add("isolated root; no inherited key, grants or autostart");
   string a=Path.Combine(work,"A"),b=Path.Combine(work,"B");Directory.CreateDirectory(a);Directory.CreateDirectory(b);string source=Path.Combine(a,"source.txt"),outside=Path.Combine(b,"outside.txt");File.WriteAllText(source,"original bytes");File.WriteAllText(outside,"outside bytes");
   string id;string token=NewTask(a,"read",out id);
   Denied(()=>Call("read_text_file","task_token",token,"path",source),"pending task");ScopeStore.Approve(id,"ask",2);
   Assert(Core.Json().Serialize(Call("read_text_file","task_token",token,"path",source)).Contains("original bytes"),"approved read");
   Denied(()=>Call("write_text_file","task_token",token,"path",source,"content","bad"),"read-only write");Denied(()=>Call("read_text_file","task_token",token,"path",outside),"outside read");Denied(()=>Call("read_text_file","task_token","invalid","path",source),"wrong token");tests.Add("pending/read-only/out-of-scope/invalid capability denied; approved read works");
   foreach(string p in new[]{a+"\\..\\B\\outside.txt",source+":secret",@"\\localhost\C$\Windows\win.ini",@"C:\Windows\win.ini",Path.Combine(a,"CON.txt"),source+".",Core.Root+"\\settings.dpapi"})Denied(()=>SafePaths.Canonical(p),"path attack "+p);tests.Add("traversal, ADS, UNC, device names, system/app-data and ambiguous paths denied");
   string hard=Path.Combine(a,"hard.txt"),hardTarget=Path.Combine(b,"hard-target.txt");File.WriteAllText(hardTarget,"hard-link test only");Assert(CreateHardLink(hard,hardTarget,IntPtr.Zero),"create synthetic hard link");Denied(()=>Call("read_text_file","task_token",token,"path",hard),"hard-link escape");tests.Add("hard-link escape rejected on opened handle");
   string junction=Path.Combine(a,"junction");var mk=Process.Start(new ProcessStartInfo("cmd.exe","/c mklink /J "+Core.Q(junction)+" "+Core.Q(b)){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true});mk.StandardOutput.ReadToEnd();mk.WaitForExit();Assert(mk.ExitCode==0,"junction fixture");Denied(()=>Call("read_text_file","task_token",token,"path",Path.Combine(junction,"outside.txt")),"junction escape");tests.Add("junction escape denied");
   Call("extend_task","task_token",token,"reason","Need sibling input","scopes",Scope(b,"read"));Denied(()=>Call("read_text_file","task_token",token,"path",outside),"extension not approved");ScopeStore.Approve(id,"ask",2);Call("read_text_file","task_token",token,"path",outside);tests.Add("approval-mode extension waits for local approval");
   string id2;string token2=NewTask(a,"write",out id2);Denied(()=>ScopeStore.Approve(id2,"ask",2),"overlapping writer");Call("close_task","task_token",token);ScopeStore.Approve(id2,"log",2);Denied(()=>Call("read_text_file","task_token",token,"path",source),"closed token");Call("extend_task","task_token",token2,"reason","Logged additional path","scopes",Scope(b,"write"));Call("read_text_file","task_token",token2,"path",outside);Assert(File.ReadAllText(ScopeStore.AuditPath).Contains("scope_auto_extended"),"automatic expansion audit");tests.Add("overlapping writer blocked; closed task revoked; user-selected logged expansion works");
   string originalHash=Core.Hash(source);Denied(()=>Call("write_text_file","task_token",token2,"path",source,"content","bad","expected_sha256","wrong"),"stale overwrite");Assert(File.ReadAllText(source)=="original bytes","stale write did not mutate");Call("write_text_file","task_token",token2,"path",source,"content","updated bytes","expected_sha256",originalHash);Assert(File.ReadAllText(source)=="updated bytes","write changed");Assert(Directory.GetFiles(Path.Combine(ScopeStore.Base,"revisions")).Any(p=>File.ReadAllText(p)=="original bytes"),"revision preserved");tests.Add("stale overwrite refused; successful overwrite preserves prior bytes");
   Denied(()=>Call("recycle_path","task_token",token2,"path",source,"reason","test","purpose","fixture","recommendation","review"),"write cannot recycle");Call("extend_task","task_token",token2,"reason","Recycle synthetic fixture","scopes",Scope(source,"recycle"));Denied(()=>Call("recycle_path","task_token",token2,"path",source,"reason","","purpose","fixture","recommendation","review"),"reason mandatory");
   var rec=Obj(Call("recycle_path","task_token",token2,"path",source,"reason","Synthetic replacement","purpose","Fixture for test","recommendation","review"));string rid=(string)rec["recycle_id"];Assert(!File.Exists(source),"removed from source");var rr=ScopeStore.Load().recycle.Single(r=>r.id==rid);Assert(File.ReadAllText(rr.stored)=="updated bytes","trash bytes retained");File.WriteAllText(source,"new conflicting file");Denied(()=>ScopeStore.Restore(rid),"restore never overwrites");File.Move(source,Path.Combine(a,"conflict-kept.txt"));ScopeStore.Restore(rid);Assert(File.ReadAllText(source)=="updated bytes","restored same bytes");tests.Add("recycle requires permission and reason; private bin retains bytes; restore collision denied; restoration succeeds");
   Call("extend_task","task_token",token2,"reason","Directory negative test","scopes",Scope(a,"recycle"));Denied(()=>Call("recycle_path","task_token",token2,"path",a,"reason","test","purpose","fixture","recommendation","review"),"directory with junction/hardlink");Assert(Directory.Exists(a),"directory retained");tests.Add("recursive recycle refuses linked content without moving directory");
   string large=Path.Combine(a,"large.bin");using(var f=new FileStream(large,FileMode.CreateNew)){f.SetLength(32L*1024*1024);}Environment.SetEnvironmentVariable("PCBRIDGE_TEST_CHUNK_DELAY_MS","1050");var watch=Stopwatch.StartNew();var job=Obj(Call("start_job","task_token",token2,"kind","hash_file","source",large));string jid=(string)job["job_id"];Assert(watch.ElapsedMilliseconds<3000,"job call returned quickly");
   Dictionary<string,object> status;do{Thread.Sleep(300);status=Obj(Call("job_status","task_token",token2,"job_id",jid));if(watch.Elapsed.TotalSeconds>55)throw new Exception("Job test deadline");}while((string)status["state"]=="queued"||(string)status["state"]=="running");Assert((string)status["state"]=="completed"&&watch.Elapsed.TotalSeconds>30,"job lives past former 30s limit");Assert((string)status["sha256"]==Core.Hash(large),"job hash correct");Environment.SetEnvironmentVariable("PCBRIDGE_TEST_CHUNK_DELAY_MS",null);tests.Add("managed job returns promptly, runs >30 seconds, reports verified SHA256");
   var copy=Obj(Call("start_job","task_token",token2,"kind","copy_file","source",source,"destination",Path.Combine(b,"copy.txt")));string cid=(string)copy["job_id"];for(int i=0;i<100;i++){Thread.Sleep(50);status=Obj(Call("job_status","task_token",token2,"job_id",cid));if((string)status["state"]=="completed")break;}Assert(File.ReadAllText(Path.Combine(b,"copy.txt"))=="updated bytes","async copy content");tests.Add("async copy writes only approved destination and reports completion");
   Environment.SetEnvironmentVariable("PCBRIDGE_TEST_CHUNK_DELAY_MS","200");var cancel=Obj(Call("start_job","task_token",token2,"kind","copy_file","source",large,"destination",Path.Combine(b,"partial.bin")));string cancelId=(string)cancel["job_id"];Thread.Sleep(350);ScopeStore.Revoke(id2);for(int i=0;i<50;i++){Thread.Sleep(100);status=Obj(Call("job_status","task_token",token2,"job_id",cancelId));if((string)status["state"]=="cancelled")break;}Assert((string)status["state"]=="cancelled","revocation cancels active job");Denied(()=>Call("read_text_file","task_token",token2,"path",source),"revoked task");Environment.SetEnvironmentVariable("PCBRIDGE_TEST_CHUNK_DELAY_MS",null);tests.Add("local revocation cancels running job; partial output retained; subsequent access denied");
   string id3;string token3=NewTask(b,"read",out id3);ScopeStore.Approve(id3,"ask",1);ScopeStore.Locked(()=>{var db=ScopeStore.Load();db.tasks.Single(t=>t.id==id3).expiresUtc=DateTime.UtcNow.AddSeconds(-1);ScopeStore.Save(db);return 0;});Denied(()=>Call("read_text_file","task_token",token3,"path",outside),"expired task");tests.Add("expiry enforced for file operations");
   string exposed=Core.Json().Serialize(ScopeEngine.Tools());Assert(!exposed.Contains("\"name\":\"run_powershell\"")&&!exposed.Contains("\"name\":\"delete_file\""),"no raw shell or purge endpoint");tests.Add("tool inventory has no arbitrary shell or permanent-delete operation");
   var interrupted=new ManagedWork{id=Guid.NewGuid().ToString("N"),taskId=id3,state="running"};File.WriteAllText(Path.Combine(ScopeStore.Base,"jobs",interrupted.id+".json"),Core.Json().Serialize(interrupted));ScopeEngine.ServerStart();Assert(File.ReadAllText(Path.Combine(ScopeStore.Base,"jobs",interrupted.id+".json")).Contains("interrupted"),"restart reconciliation");tests.Add("interrupted job marked after server restart; never falsely completed");
   Shot(new PermissionWindow(),"permissions-preview.png");Shot(new RecoveryWindow(),"recovery-preview.png");Shot(new MainWindow(),"manager-preview.png");
   File.WriteAllText(report,Core.Json().Serialize(new{ok=true,tests=tests,fixture=work,isolated_root=Core.Root,live_bridge_changed=false}));return 0;
  }catch(Exception e){File.WriteAllText(report,Core.Json().Serialize(new{ok=false,error=e.ToString(),tests=tests,fixture=work,isolated_root=Core.Root,live_bridge_changed=false}));return 1;}
 }
}